### ISSUE TITLE
SMV - vector slice - skip

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11439]
Hi,

I would like to request a feature/fix in SMV. 

The skip function in SMV vector slices allows diluting the number of vectors. But when the cell size of the mesh edges are not factor of skip input, the alignment of the vectors gets distorted. It seems skipping is done in each mesh with a reference point of respective mesh corner. 

For a solution, I suggest using a common reference point for all meshes instead of individual meshes. I believe this will resolve the issue.  

Thank you for your consideration. 

No skipping:

![image](https://user-images.githubusercontent.com/26166281/218048567-69a7a692-d593-46c6-a27d-a11b26409354.png)

Skipping is increased to 2. The separation lines are visible near the mesh boundaries:
![image](https://user-images.githubusercontent.com/26166281/218048595-7ebfe576-f1d1-4c63-85bb-4e33a0fb1aa4.png)

Mesh division:
![image](https://user-images.githubusercontent.com/26166281/218050209-3340cb59-4d60-4219-b8d8-acb92b14a812.png)

&HEAD CHID='untitled'/
&TIME T_END=15.0/
&DUMP DT_SLCF=5.0/

&MESH ID='Mesh01-01', IJK=17,31,4, XB=0.0,3.4,0.0,6.2,0.0,0.8/
&MESH ID='Mesh01-02', IJK=23,19,4, XB=0.0,4.6,6.2,10.0,0.0,0.8/
&MESH ID='Mesh01-03', IJK=33,19,4, XB=3.4,10.0,0.0,3.8,0.0,0.8/
&MESH ID='Mesh01-04', IJK=27,19,4, XB=4.6,10.0,6.2,10.0,0.0,0.8/
&MESH ID='Mesh01-05', IJK=33,12,4, XB=3.4,10.0,3.8,6.2,0.0,0.8/

&SURF ID='Surface01',      RGB=26,204,26,      VOLUME_FLOW=-3.0/

&VENT ID='Vent', SURF_ID='OPEN', XB=4.440892E-16,1.322587,10.0,10.0,-8.881784E-15,0.8/ 
&VENT ID='Vent01', SURF_ID='Surface01', XB=8.598053,10.0,10.0,10.0,-7.993606E-15,0.8/ 

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice', PBZ=0.38332/

&TAIL /

**Comment by gforney** [comment]
Good idea. Ill take a look

**Comment by gforney** [comment]
smokeview posted here should behave now the way you suggest.  let me know if you still see the old behavior.  thanks for the suggestion
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by Er9y714** [comment]
Hi Glenn,

Thank you for your response. 

- I checked the shared SMV and I still see unalignment. 

![image](https://user-images.githubusercontent.com/26166281/218705869-f601d5a0-9b2e-46aa-a728-40ebfd288771.png)


- I notice some rectangular shapes in the regular slice file

![image](https://user-images.githubusercontent.com/26166281/218706353-0e46f228-cd8a-4b7e-bcc9-a2973f43fb4e.png)



- Colors are also odd. 

![image](https://user-images.githubusercontent.com/26166281/218706456-9e5e2c75-dc86-4f4d-98ae-d15b1d2706b2.png)

**Comment by gforney** [comment]
Can you upload your case

**Comment by Er9y714** [comment]
Here you are
[untitled.zip](https://github.com/firemodels/fds/files/10731571/untitled.zip)

**Comment by gforney** [comment]
try smokeview posted here.  skipping should be fixed.  skip is 2 in attached images. I also found a line of code missing that fetched the vector line (not point) color).  so that may have caused the color anomalies you saw
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=share_link
![case_start](https://user-images.githubusercontent.com/12403014/218825773-85f9be66-a769-41f8-9358-73be191083a3.png)
![case_end](https://user-images.githubusercontent.com/12403014/218825804-82c18b98-7b56-4b69-ac09-c6b7aca97c4c.png)

**Comment by Er9y714** [comment]
Alignment works! 

But I still see these squares on the regular slice file:

![image](https://user-images.githubusercontent.com/26166281/219377465-e5fb3403-5cf4-4d9a-802e-f82fa5639970.png)


If I change the cell size the first mesh and refine it x2, then alignment issue is present once again. Do you think you can help with different mesh sizes?

![image](https://user-images.githubusercontent.com/26166281/219379231-667a5003-e6b5-4b94-b44b-4785d5b16d33.png)


I attach the case with different grid sizes (first mesh is finer than others):

[untitled_2.zip](https://github.com/firemodels/fds/files/10756478/untitled_2.zip)



Thank you.

**Comment by drjfloyd** [comment]
It could be that the mesh change and the skip are coprime (mesh factor of 3 and skip=4). You could also have a TRNX on one mesh but not the other as long as grid edges still lineup. You may not always be able to get a nice lining up of vectors in all cases.

**Comment by gforney** [comment]
open the slice settings dialog box and see if the "outline" checkbox is checked.  

I think I have a fix for the skipping but since I've posted 2 smokeview's already I'm going to test it some more

![slice_settings](https://user-images.githubusercontent.com/12403014/219535987-904116a8-fa7c-488d-acb9-79ac9287da91.png)

**Comment by Er9y714** [comment]
Unfortunately, outlines checkbox did not change the result.

**Comment by Er9y714** [comment]
> open the slice settings dialog box and see if the "outline" checkbox is checked.
> 
> I think I have a fix for the skipping but since I've posted 2 smokeview's already I'm going to test it some more
> 
> ![slice_settings](https://user-images.githubusercontent.com/12403014/219535987-904116a8-fa7c-488d-acb9-79ac9287da91.png)

Disabling both solid and gas outline solves this issue. (This was your recommendation in other issue thread)

 
Regarding the other request: _vector skip for varying mesh sizes_. If you decide not to develop this feature, you can close the issue. Thank you very much.

**Comment by gforney** [comment]
I've been working on changing where we post test bundles .  changing from google drive to github.  I"ll post a smokeview and give you a new link later today to make sure you are working with latest smokeview

**Comment by gforney** [comment]
1.  test smokeviews are posted at github now - link should not change.  
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

2.  images are from this smokeview for your untitled2 case you posted earlier.  I selected uniform and unchecked uniform checkbox for two attached images.  vectors should be spaced uniformly when you select uniform.  this assumes that the coarse grid is a multiple of the fine grid.

3.  solid color, outline and points checkboxes are applied separately for gas, solid and cutcell (this is a immersed geometry region) regions.  Part of the bug you saw was that smokeview "thought" the gas was a solid.  if you select gas then you should be able to check or unhceck "solid colors", "outlines" and "points" have have these show or hide in the gas. likewise if you select the radio button solid and select or unselect "solid colors", "outlines" "points" then these drawing types should show or hide in the solid (of course you would need to hide the obstacels then to see the slice where the obstacle would have been.

you will be one of the first to download smokeview from this link so let me iknow if you have any problems


![non_uniform_vectors](https://user-images.githubusercontent.com/12403014/225096906-53e9888b-37d3-49fb-a23b-d439656f13a8.png)
non-uniform spaced vectors

**Comment by gforney** [comment]
![uniform_vectors](https://user-images.githubusercontent.com/12403014/225099181-f081b3a8-b281-45ba-bc3a-c54bb9f7680b.png)
 uniform spaced vectors

**Comment by gforney** [comment]
![slice_dialog](https://user-images.githubusercontent.com/12403014/225101990-b11f5cc7-7bc8-4d9e-84c0-6ccb1d2fa04c.png)

**Comment by Er9y714** [comment]
I confirm that skip and lines works without any problems. Thank you very much @gforney!
