### ISSUE TITLE
Undefined HEAT_OF_REACTION causes case failure

### ISSUE THREAD

**Issue by Bravnewor** [firemodels/fds#12936]
**Describe the bug**
When I was trying to define liquid fuel, I found that not defining HEAT_OF_REACTION passed the check, but caused the program to fail.

**To Reproduce**
Run the attached case.
[case.txt](https://github.com/firemodels/fds/files/15317007/case.txt)

**Expected behavior**
Set a default value for HEAT_OF_REACTION for liquid fuels or return an error message

**Desktop (please complete the following information):**
 - OS: windows11
 - Version: FDS-6.9.1-0-g889da6a-release

**Comment by rmcdermo** [comment]
Thanks for the report.  Looks like this has been fixed, as the latest source runs your test without failing, though since the case is not completely set up it does not really do anything so I cannot attest that all is ok (however, I appreciate the minimal test case!).  Please try the nightly build on a full case and see if things work for you.

https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST

**Comment by Bravnewor** [comment]
Sorry, but nightly builds don't seem to work. I used the FDS-6.9.1-211-g997c1d8-nightly version. The failure still happens on my computer.
My liquid fuel case is built according to 9.2.6 of the user guide, and the failure is reproduced by simply deleting the "HEAT_OF_REACTION = 837" line

**Comment by rmcdermo** [comment]
OK, we will take a look.

**Comment by mcgratta** [comment]
The logic for liquid fuels was flawed. I fixed it, but in the meantime, set a positive value of HoR. The code will now produce an ERROR if you do not.

**Comment by Bravnewor** [comment]
Thx for your continued maintenance and prompt replies!
