### ISSUE TITLE
WARNING: Minimum density, 0.120 kg/m3, clipped in Mesh 1

### ISSUE THREAD

**Issue by Mikkelmhfire** [firemodels/fds#14452]
**Describe the bug**
Im trying to simulate a 5MW fire inside a large storageunit. Whenever im reaching 200 -250 seconnds in the simulation im getting this error: WARNING: Minimum density, 0.120 kg/m3, clipped in Mesh 1.

I have tried to locate the corrupted cells by using Plot3D data on pressure and temperature, but i cant find it. 

![Image](https://github.com/user-attachments/assets/00732b25-36a3-4c4b-9bb2-f4854afce3be)

Please help. I've attached the FDS file.

**Desktop (please complete the following information):**
Windows 11
Pyrosim 2024.02.1209

[Grundmodel.log](https://github.com/user-attachments/files/19546395/Grundmodel.log)

**Comment by rmcdermo** [comment]
Did the simulation crash?  This is only a warning.

You can change the clip limits using the `CLIP` namelist.  For example:
```
&CLIP MINIMUM_DENSITY=0.01/
```

**Comment by Mikkelmhfire** [comment]
> Did the simulation crash? This is only a warning.
> 
> You can change the clip limits using the `CLIP` namelist. For example:
> 
> ```
> &CLIP MINIMUM_DENSITY=0.01/
> ```

Yes the simulation did crash. And thanks for the advice but i would rather not since that could potentially lead to more unpsychical activities.

**Comment by mcgratta** [comment]
Look for regions of unphysically high temperatures in the mesh indicated in the warning statement. This might give you a clue as to something in the simulation that is causing a problem. Sometimes this warning statement just indicates that the temperature spiked in one grid at one time step, but the simulation continued. However, repeated warnings and ultimately a Numerical Instability indicate that something has gone very wrong. Then you need to look at the Plot3d output in Smokeview to see where the velocity vectors have become fictitiously large.

**Comment by mcgratta** [comment]
You can also look at the `.out` file. Assuming that the number of meshes is less than or equal to 32, the end of the `.out` file would indicate where the instability occurred. For each mesh, look at `Max CFL Number` and in the problem mesh you will see, usually, a large number indicating that the CFL number has risen far beyond 1. The coordinates are given here
```
       Max CFL number:  0.74E+00 at (72,43,23)
       Max divergence:  0.19E+02 at (69,47,23)
       Min divergence: -0.27E+01 at (72,21,24)
       Max VN number :  0.61E+00 at (70,20,23)
```

**Comment by mcgratta** [comment]
I am running the case. It seems to be unnecessarily complicated. Has PyroSim broken up the entire geometry into single block `OBST`s? It has taken a long time just to start the job.

**Comment by Mikkelmhfire** [comment]
> I am running the case. It seems to be unnecessarily complicated. Has PyroSim broken up the entire geometry into single block `OBST`s? It has taken a long time just to start the job.

Yes, this option was activated (where every single obstruction is forced into single cells). I deactivated this and switched from VLES to LES. So far so good. 

Ill try to run the scenario again with VLES, and see if the single cell obstruction was the reason for the error message - Stay tuned.

**Comment by mcgratta** [comment]
The original case failed for me in a similar way to yours. I'm going to try a few things

* Reduce `MINIMUM_DENSITY`
* Remove `RADIATION=F`
* Remove `SUPPRESSION=F`

When you turn off radiation, you eliminate the ability of FDS to radiate more energy from hot spots. These hot spots might be causing the density to drop below the cut-off. Similar for `SUPPRESSION`. Why let things burn when there is no oxygen?

**Comment by mcgratta** [comment]
I started two jobs. In one, I set a `MINIMUM_DENSITY=0.01`. In the other, I turned `RADIATION` and `SUPPRESSION` back to their default values of `T`. Both cases are still running long past the point of failure. We are considering whether to reduce the default `MINIMUM_DENSITY`. As for the other two parameters, we don't recommend that they be turned off unless you are doing some kind of parameter study or diagnostic test. As I said above, these features not only represent the true physics, but they also tend to reduce the impact of a spurious burst of high temperature related to the turbulent combustion model and the mixed-is-burnt assumption.

**Comment by Mikkelmhfire** [comment]
A little update - it has been solved. Not quit sure what the course was, but i recon it to be the "force every obstruction to be a signle cell" function.

I also added readiation.

Thanks for the support MCgratta :)

**Comment by mcgratta** [comment]
Possibly, but I would still not recommend that you turn off radiation and suppression.
