### ISSUE TITLE
Droplet evaporation on HT3D walls

### ISSUE THREAD

**Issue by Vojta-Salek** [firemodels/fds#14521]
**Describe the bug**
Hello, I am testing water droplets impacting an `HT3D` wall. Compared to an `HT1D` wall, the surface temperatures on the `HT3D` wall show unphysically high or low values, suggesting that the droplet evaporation algorithm is not functioning correctly for `HT3D`. The unphysical values occur even for very 'numerically friendly' conditions, such as droplets at 15°C hitting walls at 22°C.

I have also noted that this discrepancy between HT3D and HT1D disappears for highly conductive walls. However, there still appears to be a fundamental difference in how HT3D and HT1D handle droplet evaporation.

**To Reproduce**
Run the attached simple case and plot boundary wall temperature. `HT1D` wall behaves as expected, while `HT3D` walls produce unphysical temperatures. 
[Particle_negative.txt](https://github.com/user-attachments/files/19788508/Particle_negative.txt)

**Screenshots**
![Image](https://github.com/user-attachments/assets/74776c5d-ed14-46e1-ad65-08c9b6b52978)

**Versions:**
- OS: **Win10 Pro 22H2**
- FDS: **FDS-6.10.0-100-gecba0a2-nightly**

**Comment by mcgratta** [comment]
I think I see the problem here. The convective and radiative heat fluxes at the surface are written _implicitly_; that is, they make use of the wall temperature at the start and end of the time step. The heat flux from the water droplets do not do this, and for the `HT3D` case, it appears that the heat flux from the water is causing a numerical instability. I don't understand exactly why this is worse for the 3D case compared to the 1D, but in any case, I think we need to rewrite the water cooling term implicitly.

**Comment by drjfloyd** [comment]
The explicit water cooling is used to ensure the heat transfer to/from the drop matches that to the solid. If the wall is made implicit and allowed to change from what was used in the droplet routine, then drop evaporation will not conversve energy.

**Comment by mcgratta** [comment]
I notice that there is an assumption in the droplet heat transfer calculation that the underlying solid is 1-D. I don't know if that is the cause of the problem, but it is my first guess. The 1-D and 3-D algorithms treat the boundary conditions in the same way.

**Comment by mcgratta** [comment]
Add `RUNNING_AVERAGE_FACTOR_WALL=0.95` to the `PART` line. This is only a temporary fix. The problem is that each droplet represents a substantial amount of water and adding this factor smooths the water field on the surface. I am looking for a way to do this automatically without you having to set it.

**Comment by mcgratta** [comment]
I have changed the default smoothing factor for droplets so that we do not see large amounts of water in one grid cell.,

**Comment by mcgratta** [comment]
The latest nightly build should work better in this case.

**Comment by Vojta-Salek** [comment]
Thank you! Is there anything else in the new nightly build besides `RUNNING_AVERAGE_FACTOR_WALL=0.95`? I’ll continue testing droplets in `HT3D` and will let you know if I encounter further uncertainties. Occasionally, I get the error `forrtl severe (157): Program Exception - access violation` shortly after introducing particles. I’ll try to simplify the case and identify the trigger.

One minor note: when launching a case with particles, a warning appears—`Droplet heat transfer is not predicted when a droplet is on a SURF with a specified ADIABATIC, NET_HEAT_FLUX, or CONVECTIVE_HEAT_FLUX`. I believe this information is missing from the Guides. Also, it seems heat transfer isn’t predicted when `TMP_FRONT` is specified for a thermally thin obstruction via `VENT`.

**Comment by Vojta-Salek** [comment]
Thank you for the confirmation. I spoke too soon regarding `TMP_FRONT`, I underestimated the amount of water in the particles and their heat capacity. Heat transfer does occur; it just takes some time. The time required to evaporate a given amount of water matches a back-of-the-envelope calculation.

The created demo case is below, not sure if it is somehow useful for you. 

[TMP_FRONT.txt](https://github.com/user-attachments/files/19886170/TMP_FRONT.txt)

One thing I noticed is a strange wall temperature pattern around the heater (set to `TMP_FRONT = 1200` via a `VENT`). I would expect a gradual temperature drop with increasing distance from the source, but there’s a cold gap in the first row of cells adjacent to the source. The image shows the bottom side of the burner, with the cold row highlighted. This gap appears even when particles are not stationary and move freely over the surface (using the default `HORIZONTAL_VELOCITY`).

![Image](https://github.com/user-attachments/assets/c90c5ffa-c3b6-449b-9496-86cc67a344b2)

**Comment by Vojta-Salek** [comment]
Oh, I'm stupid, I had deleted the `CELL_SIZE_FACTOR` and `STRETCH_FACTOR` I usually use when simplifying the demo as much as possible.. It's fixed now, and from my perspective, the issue is resolved.

I'm still dealing with a `forrtl severe (157): Program Exception - access violation` in some cases, but I can open a separate issue for that later.

Let me know if there's anything else I should test in this context.

**Comment by mcgratta** [comment]
You are not stupid. We still do not have a simple strategy for doing internal noding. Plus, in your case, there is a fictitiously low temperature on the backside of the obstruction in the beginning. I know why this is happening, but I need to think about a cure. It has to do with the basic 3-D methodology.

**Comment by Vojta-Salek** [comment]
Understood. If it only affects the back wall for a limited time, it is a manageable fault I can work with. Should I create a new issue for the 3-D methodology to preserve the idea?

From my perspective, the droplet evaporation issue is resolved. I'm still dealing with a `forrtl severe (157): Program Exception - access violation` in some cases, but I can open a separate issue for that later.

Please let me know if there's anything else I should test in this context.
