### ISSUE TITLE
bug with RENDERDOUBLEONCE command

### ISSUE THREAD

**Issue by borimseo** [firemodels/fds#4441]
When using the scrip command “RENDERDOUBLEONCE”  to render the current scene at double resolution, there is a bug for image files created. They no longer go into the designated directory folder and the file name doesn’t come out as it is assigned in the script. This only happens when using “RENDERDOUBLEONCE” command. Everything works fine as it should be with “RENDERONCE” command. Is there any way to fix this?

**Comment by gforney** [comment]
should be fixed in latest smokeview.  download the latest smokeview, version 6.4.1 and report back whether this smokeview works for you

**Comment by borimseo** [comment]
Version 6.4.1 fixed the problem with the file name, but it still does not go into the designated directory folder with "RENDERDIR" command.

**Comment by sbenkorichi** [comment]
Is this still an issue?

**Comment by borimseo** [comment]
Yes. I downloaded the latest smokeview, but it still doesn't show up in the designated folder. Moreover, I cannot produce contour anymore with rendering.

**Comment by gforney** [comment]
can you upload a case and script file that demonstrates the problem

**Comment by sbenkorichi** [comment]
Glenn, 
I had a look to this issue. Find below a simple case that reproduce the issue. 
Looks like RENDERDOUBLEONCE isn't linked with RENDERDIR, and only output stuff in the same input file. 

[smv-renderdoubleonce.tar.gz](https://github.com/firemodels/fds/files/1308576/smv-renderdoubleonce.tar.gz)

**Comment by gforney** [comment]
thanks, I'm taking a look at this now

**Comment by gforney** [comment]
should be fixed in smokeview's posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
Thanks Glenn,
Works like a champ ! 
This now can be closed.

**Comment by sbenkorichi** [comment]
Glenn,
I think this thread should be closed. The function works well, and the user can report back if something is not working for him.
