### ISSUE TITLE
Smokeview S3D Smoke rendering

### ISSUE THREAD

**Issue by JWWilliamson** [firemodels/fds#5588]
I have been running one of the newer Validation cases (200 kW fire in a corner, tests run at NIST) using FDS 6.5.3 and Smokeview 6.4.4. I am currently running some of the other cases as well, but they are not as far along.

https://github.com/firemodels/fds/blob/master/Validation/NIST_NRC_Corner_Effects/FDS_Input_Files/corner_200_kW.fds

When I run these cases, two issues happen.
1. No smoke ever loads in the first grid mesh surrounding the fire.
2. The smoke mysteriously vanishes starting at about 1800 s when the fire is moved 10cm away from the corner. It is visibly gone by about 2700 s even though the fire persists throughout. 

These are low sooting fires, so this may be a data cutoff for point 2, but I played with the visualization settings and smoke albedo to make some images that attempt to show the issue. This does not appear to impact any other functionality, so I think it is a minor bug.

![corner_200_kw_0238](https://user-images.githubusercontent.com/17410570/31726739-c0060d30-b3f5-11e7-8664-da373b3a5262.png)

![corner_200_kw_0238](https://user-images.githubusercontent.com/17410570/31726799-e1695e1e-b3f5-11e7-9455-06b92225a871.png)

![corner_200_kw_0301](https://user-images.githubusercontent.com/17410570/31726804-e6edb0a6-b3f5-11e7-9d1b-f085b820c998.png)

**Comment by sbenkorichi** [comment]
Couple bugs were fixed, install the latest version from here and retest and report back
https://pages.nist.gov/fds-smv/downloads.html

**Comment by rmcdermo** [comment]
@JWWilliamson you may also want to look at Dialogs > Data Bounds > 3D Smoke and set the "Load 3D Smoke/HRRPUV when..." to something low.
![screen shot 2017-10-18 at 11 36 43 am](https://user-images.githubusercontent.com/4418497/31727888-d2858636-b3f8-11e7-8cb2-e662f2fe9747.png)

**Comment by JWWilliamson** [comment]
The new version appears to have fixed point 1. All meshes now visualize smoke.
I have the Load 3D smoke/HRRPUV when set to 0, 0 and point 2 still persists. The smoke disappears while the fire persists.

**Comment by mcgratta** [comment]
Have you run this by Jason? Is he seeing the same trouble? Could be a newer version of SMV will fix the problem.

**Comment by gforney** [comment]
before we move forward, try the smokeview here.  Earlier I pushed up a test smokeview that implemented an experimental smoke visualization.  Don't know if you were using that one.  The version I pushed up now is using the original algorithm.  
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by JWWilliamson** [comment]
The problem persists with this version. 
It may not be a problem with smokeview. It may be that the fire soot yield drops to zero when the fire base moves. I don't know at this point as I did not add any species diagnostic outputs to any of the runs.

**Comment by mcgratta** [comment]
There is still something funky going on here. I'll take a look at it.

**Comment by mcgratta** [comment]
Glenn, here is a simple case that illustrates the problem. The box is filled with a uniform amount of smoke, but the visibility changes depending on the mesh resolution. Run the case (single process is fast enough) and look at the 3D smoke.
```
&HEAD CHID='smoke' /

&MESH IJK=28,36,38, XB=0.0,1.375,0.0,1.75,0.0,1.9, MULT_ID='fine_mesh' /
&MULT ID='fine_mesh', DX=1.375, DY=1.75, DZ=1.9, I_UPPER=1, J_UPPER=1, K_UPPER=1 /

&MESH IJK=28,36,38, XB=0.0,2.75,3.5,7.0,0.0,3.8 /

&MESH IJK=28,36,38, XB=0.0,2.75,0.0,3.5,0.0,3.8, MULT_ID='mesh' /
&MULT ID='mesh', DX=2.75, DY=3.5, I_LOWER=1, I_UPPER=3, J_UPPER=1 /

&SURF ID='WALL', DEFAULT=.TRUE., COLOR='INVISIBLE' /

&TIME T_END=1. /

&SPEC ID='SOOT' /

&INIT XB=0,11,0,7,0,3.8, MASS_FRACTION=0.00001, SPEC_ID='SOOT' /

&SLCF PBZ=3.30, QUANTITY='MASS FRACTION', SPEC_ID='SOOT', CELL_CENTERED=.TRUE. /

&TAIL/
```

**Comment by mcgratta** [comment]
Glenn writes:

 think this is a numerical problem.  smokeview (in fds) is computing

alpha = 255*(1-exp(-Km*S*DX) .  When I plug in the numbers for your case I get alpha ~1.  The problem is that alpha on the video card only has 8 bits of precision.  So the errors accumulate pretty fast when I combine slices.  I'm looking to see if there are options to get more precision.  

Smokeview has another way of computing smoke by use a 3d slice file of soot density directly.  It uses volume rendering to do the integration using full precision.  When I use this method things look ok.

**Comment by mcgratta** [comment]
Whoops, closed by mistake.
