### ISSUE TITLE
Divide by zero in HVAC

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8512]
This affects lots of the PRISME cases
```
Job ID string    : PRS_D2

forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source
fds_impi_intel_li  000000000C2B1E6B  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B53DDB9B5F0  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000003793072  wall_routineshvac        2403  wall.f90
fds_impi_intel_li  000000000378E911  wall_routines_mp_        2353  wall.f90
fds_impi_intel_li  000000000365785E  wall_routines_mp_          61  wall.f90
fds_impi_intel_li  0000000003F6CEA8  MAIN__                    648  main.f90
fds_impi_intel_li  0000000000409222  Unknown               Unknown  Unknown
libc-2.17.so       00002B53DFA1A505  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  0000000000409129  Unknown               Unknown  Unknown
srun: error: blaze033: task 0: Aborted (core dumped)
```

**Comment by drjfloyd** [comment]
Cell 51 1 1 has ONE_D%ZZ_G(1)=0. This is not a gas cell as it is inside the two-cell thick wall with the door.  This wall cell shouldn't have a NODE_INDEX assigned to it.  Something mus be wrong in the HVAC BC initialization.

**Comment by mcgratta** [comment]
Just as an FYI, I don't think the basic set up of these cases has changed the last few years, and the cases ran in Feb 2020. So a git bisect might find it.

**Comment by drjfloyd** [comment]
Should be fixed now.  Ran PRS_D2 to +20 s and results were looking OK.

**Comment by mcgratta** [comment]
Thanks

**Comment by mcgratta** [comment]
These cases still fail. I just ran, for exampe, PRS_SI_D2, and it still fails after one time step.

**Comment by drjfloyd** [comment]
Is this based on the source after my commit this morning?

**Comment by mcgratta** [comment]
Yes

**Comment by drjfloyd** [comment]
I'll look at it.  

I just noticed in the input file that these inputs specify a constant flow for both supply and exhaust. Unless the fan speed was controlled to maintain constant flow, under fire conditions these flow rates probably varied quite a bit. These inputs should probably have a fan curve.

**Comment by mcgratta** [comment]
These are the French PRISME experiments. There are openings to the
atmosphere at various points in the network.

>

**Comment by drjfloyd** [comment]
And as the pressure in the fire room changes it will change the amount of flow that can enter or exit.

**Comment by mcgratta** [comment]
The predicted and measured flow rates for these cases are good. What results do you see that look incorrect?

**Comment by drjfloyd** [comment]
There must be enough pressure relief through the ambient ducts to negate the compartment effects.

This current bug is related to setting initial pressures in the duct network. I use the pressure ramp so I can match any user specified lapse but my timing is off in that the pressure ramp isn't defined until init and we setup hvac in read. I'm surprised none of the ashrae test cases failed because of this. Also realize I need to update ZS_MIN and ZF_MAX for the case where a users specifies a node outside the elevation of the meshes.

**Comment by drjfloyd** [comment]
Does READ_WIND need to be where it is in list of read routines or do you think it can be moved to just after READ_HVAC?  One of things in this PRISME case is the hvac nodes are outside the meshes so the pressure and temperature RAMPs setup by wind need to account for that so I can then later use them to initialize the system.

**Comment by mcgratta** [comment]
No, because WIND sets up the vertical profile of the atmosphere, and this
needs to be established early.

>

**Comment by mcgratta** [comment]
What has been done up to now with XYZ positions that were higher than the
ZF_MAX?

>

**Comment by drjfloyd** [comment]
I don't think I ever ran a case myself where XYZ  was outside of  ZF_MAX and ZS_MIN.  

For a long time HVAC just used the simple temperature lapse equation in HVAC. So this was OK before you added the WIND stuff but After the Monin-Obukhov length was added I no longer did the same thing as WIND did for the profiles and that wound up being a potential problem. My fix for that introduced a bug that I didn't notice until you discovered it with the PRISME cases.

We need to have the pressure and temperature ramps encompass the HVAC limits otherwise if II query the ramps outside the bounds those nodes won't have the proper pressures and we will get spurious flows at the onset that could drive the HVAC solution to an incorrect answer.  

What uses the vertical profile before we finish reading the input file?

**Comment by mcgratta** [comment]
Actually, the vertical profile is set up in init.f90, long after reading.
So we may be able to move READ_WIND. Let me look.

>

**Comment by mcgratta** [comment]
Lots of potential problems. How bad would it be to just assume dp/dz=-rho*z
?

>

**Comment by drjfloyd** [comment]
At one point that is what HVAC did. Not doing the same as the gas phase was causing problems.

I guess I will need to do HVAC as two reads. One that just gets ductnode elevations to feed into READ_WIND and a second read to actually set it up (setting up the HVAC  arrays requires setting aside space for LEAK_PATH so I can't READ_HVAC for real until I know how many LEAK_PATHS there are). This isn't a huge deal, just not as easy as moving READ_WIND a few lines down would have been.

**Comment by mcgratta** [comment]
I can tell you in about 15 minutes if there is a major problem with moving
READ_WIND. Hold on. I'll run the verification cases in debug mode and look
for trouble.

>

**Comment by mcgratta** [comment]
No obvious divides by zero or seg faults in the verification cases. I'm going to commit the change and let firebot check it. Don't make any other changes. Let's just see if we can reposition the READ_WIND routine.

**Comment by drjfloyd** [comment]
The two warnings last night seemed to be unrelated to wind. I pushed up changes to have the pressure and temperature ramps account for node elevations outside of mesh boundaries and moved the initialization of duct nodes to after the pressure ramp is established.  The PRS_SI_D2 and PRS_D2 cases both start running now.

**Comment by drjfloyd** [comment]
Closing
