### ISSUE TITLE
Batch job submission failed: Node count specification invalid

### ISSUE THREAD

**Issue by ahsadeghi** [firemodels/fds#8639]
Hi, 
I get the following error when running the validation suite of Nist_Pool_Fires. Could anyone please give me some idea how to solve it? I don't see this problem with some other validation cases that I am running (Heat Flux to Target).

![image](https://user-images.githubusercontent.com/51397945/88739020-2bbbdc00-d142-11ea-976a-55498e0af9fc.png)

**Comment by drjfloyd** [comment]
Update your repository.  There was an error in the run_all.sh script for that test series that was fixed recently.  You have the old script which is trying to run 12 processes as 8 processes each on 2 nodes and the new script fixed that as 12 processes as 6 processes each on 2 nodes.

**Comment by ahsadeghi** [comment]
I replaced the Run_All.sh, now the numbers match (processes, nodes and processes per node) but still the same error is shown.
 
![image](https://user-images.githubusercontent.com/51397945/88782285-1375ac80-d196-11ea-8fdd-007de32acaeb.png)

**Comment by mcgratta** [comment]
Tell us more about what you are doing. It appears that you have cloned the fds git repository. Are you running the qfds.sh script, or are you running the Run_All.sh script that appears in the NIST_Pool_Fires directory?

**Comment by ahsadeghi** [comment]
Hi Kevin, thanks for your consideration. I am running the validation suite on a cluster. Yes, I have. I am running the cases using Run_All.sh which exist in the directory of the validation suites. It works for Hamins_Gas_Burners and Fleury_Heat_Flux but I get the mentioned error when running NIST_Pool_Fires. I copy the full message here. Actually two of them are submitted but the others are not. 

```
         Input file:NIST_Acetone_Prescribed_2cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:2
          Processes:12
 Processes per node:6

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Acetone_Prescribed_1cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:2
          Processes:12
 Processes per node:6

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Acetone_Prescribed_0p5cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:3
          Processes:24
 Processes per node:8

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Ethanol_Prescribed_2cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:2
          Processes:12
 Processes per node:6

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Ethanol_Prescribed_1cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:2
          Processes:12
 Processes per node:6

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Ethanol_Prescribed_0p5cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:3
          Processes:24
 Processes per node:8

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Methanol_Prescribed_2cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:2
          Processes:16
 Processes per node:8

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Methanol_Prescribed_1cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:2
          Processes:16
 Processes per node:8

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Methanol_Prescribed_0p5cm.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:4
          Processes:32
 Processes per node:8

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Methanol_1m_pan_1cm_grid.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:12
          Processes:96
 Processes per node:8

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Methanol_1m_pan_2cm_grid.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:2
          Processes:12
 Processes per node:6

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Methanol_1m_pan_4cm_grid.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:1
          Processes:2
 Processes per node:2

Submitted batch job 3046288
         Input file:NIST_Methanol_1m_pan_1cm_grid_predicted.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:12
          Processes:96
 Processes per node:8

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Methanol_1m_pan_2cm_grid_predicted.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:2
          Processes:12
 Processes per node:6

sbatch: error: Batch job submission failed: Node count specification invalid
         Input file:NIST_Methanol_1m_pan_4cm_grid_predicted.fds
         Executable:/scratch/project_2003185/firemodels/fds/Validation/NIST_Pool_Fires/fds_impi_intel_linux_64_1
           Intel MPI
            Modules:StdEnv git/2.25.4 intel/19.0.4 intel-mkl/2019.0.4 intel-mpi/18.0.5
   Resource Manager:SLURM
              Queue:small
              Nodes:1
          Processes:2
 Processes per node:2

Submitted batch job 3046289
FDS cases submitted

```

**Comment by mcgratta** [comment]
The error message `Batch job submission failed: Node count specification invalid` is issued by the SLURM job manager, and it means that you have asked for more nodes than the partition (Queue) allows. My guess is that the partition named `small` is limited to a single node. `Hamins_Gas_Burners` and `Fleury_Heat_Flux` worked because all these jobs use a single MPI process; that is, one core on one node. Look in the `Run_All.sh` and if the job requires more than one core, you will see `-p N -n M` where `N` is the number of MPI processes and `M` is the number of processes per node. Since we run our cases on a cluster with nodes of 8 cores, that is why you see `M` is less than or equal to 8.

**Comment by ahsadeghi** [comment]
Thanks, now I can run them with ``` large ``` partition. 
I close this issue.
