### ISSUE TITLE
heat transfer through a thin obstruction

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#8782]
The heat transfer through an infinitely thin sheet leads to an increasing gas temperature. The gas temperatures in the cold and hot compartments are outside the limit temperatures (min. 20°C and max. 500°C).

[partition.fds.txt](https://github.com/firemodels/fds/files/5304588/partition.fds.txt)
![partition](https://user-images.githubusercontent.com/27724706/94670387-c9828180-0312-11eb-8915-33fa9a24daa5.jpg)

**Comment by rmcdermo** [comment]
Please try using the UGLMAT pressure solver and see if the issue persists.  Thanks

```
&PRES SOLVER='UGLMAT'/
```

**Comment by herbertTau** [comment]
It leads to the message:
ERROR: Numerical Instability - FDS stopped (CHID: partition)

**Comment by drjfloyd** [comment]
If you are using an official release version of FDS you need to define a pressure zone for each side.

**Comment by herbertTau** [comment]
After doing a run with open vents and partially partition wall I got a similarly bad result, but when using the UGLMAT pressure solver it works fine now.
Thanks

**Comment by drjfloyd** [comment]
If I add a ZONE for each side and tighten the VELOCITY_TOLERANCE it works fine without UGLMAT:

&PRES VELOCITY_TOLERANCE=1E-3,MAX_PRESSURE_ITERATIONS=50/
&ZONE XYZ=-1,0,1/
&ZONE XYZ= 1,0,1/

It takes 46 pressure iterations in the first time step, but after that it drops to single digit iterations.

**Comment by rmcdermo** [comment]
@marcosvanella Please check to make sure this works with UGLMAT as well.  Thanks

**Comment by herbertTau** [comment]
I tried it out with

&PRES VELOCITY_TOLERANCE=1E-3,MAX_PRESSURE_ITERATIONS=50/
&ZONE XYZ=-1,0,1/
&ZONE XYZ= 1,0,1/

It works better, but the temperatures of the adjacent cells to the partition wall in the left room are about 17°C. By running with UGLMAT the cells have temperatures of 20°C.

**Comment by rmcdermo** [comment]
Yes, you need nearly perfect tolerances to keep temperatures tight.  Play with velocity tolerance.

```
&PRES VELOCITY_TOLERANCE=1E-6,MAX_PRESSURE_ITERATIONS=1000/
```

**Comment by herbertTau** [comment]
The temperatures are better now, but still a little under 20°C.  I noticed that this effect is almost gone when the partition wall is one cell thick.

**Comment by mcgratta** [comment]
When the wall is thin, the velocity components at the wall must be driven
to a very very low value to maintain a perfect temperature. This is
because a small positive velocity on one side of the wall means there is a
small negative on the other. If there is a grid cell in between, it is
easier to isolate one compartment from the other.

>

**Comment by marcosvanella** [comment]
UGLMAT currently works with a single ZONE only. It should have picked up the two zones and thrown an error. I'll have a look.

**Comment by marcosvanella** [comment]
This case should work now with UGLMAT. Multiple sealed compartments (or regions with open boundaries) are handled by the solver (single global matrix, either indefinite or +ve definite). 
The case of sealed compartments + regions with open boundaries in not handled currently. Will be handled by UGLMAT when we set the solution to be done by PRESSURE ZONE, when we revisit grids at different refinement levels.

**Comment by drjfloyd** [comment]
I tried running this again. If I up tighten the tolerance for the default presure solver it works fine. On my windows laptop, when I try UGLMAT as the solver, after ten minutes it has still not started time stepping.

**Comment by marcosvanella** [comment]
Yes, that seems the case. Something related to CLUSTER_SPARSE_SOLVER and windows. UGLMAT works on the mac. Also try ULMAT (uses PARDISO instead of the cluster solver) to check that works. I'll get back to this.
