### ISSUE TITLE
BURN_AWAY and RESTART conflict

### ISSUE THREAD

**Issue by MortezaHaghighi** [firemodels/fds#8986]
Hi,

Stoped simulation midway burning away, followed by restarting the calculations, will end up in the reproduction of the initial complete geometry.
Based on my experience, it's not just an SMV visualization problem, but rather a PYRO3D code bug (a Jump in MLR curve seen in another heavy simulation).
The attached input file was forcefully stopped at about  350s and started again.

![BURN_AWAY_RESTART_BUG_0 0s](https://user-images.githubusercontent.com/56713983/99987821-94962680-2db9-11eb-80c8-546fb45ccf73.png)
![BURN_AWAY_RESTART_BUG_349 2s](https://user-images.githubusercontent.com/56713983/99987836-99f37100-2db9-11eb-98ad-8af4eac3877c.png)
![BURN_AWAY_RESTART_BUG_349 8s](https://user-images.githubusercontent.com/56713983/99987854-9e1f8e80-2db9-11eb-8b1f-ca85073f80b8.png)
![BURN_AWAY_RESTART_BUG_451 2s](https://user-images.githubusercontent.com/56713983/99987861-a081e880-2db9-11eb-9fb1-04c2eafc7bbe.png)

[BURN_AWAY_RESTART_BUG.fds.txt](https://github.com/firemodels/fds/files/5584350/BURN_AWAY_RESTART_BUG.fds.txt)

Thanks in advance.

**Comment by rmcdermo** [comment]
Thanks for the report.  I'll have a look.

**Comment by rmcdermo** [comment]
This should be fixed with PR #8990 .  Give it a try and let me know.  Good catch and nice simple test case.  Thanks.  I'm nominating this for a Boris Stock!

**Comment by MortezaHaghighi** [comment]
Overall looks fine to me. However, I still see a minor jump on the MLR curve while restarting. For example, the following figure is a result of restarting at 345 s. Other restarting times found to reproduce such a jump as well.

![MLR](https://user-images.githubusercontent.com/56713983/102762686-4c9afd00-4381-11eb-8e68-c2aad68d50b8.jpg)

**Comment by rmcdermo** [comment]
I'm trying to track it down.  The only clue I have so far is that if I set DT_RESTART to coincide with with T_END, then we do not get the kink.  So, I suspect a time-related problem, averaging, or something.

**Comment by rmcdermo** [comment]
This should be fixed with PR #9069.  Please confirm.

Before we close this, we should implement a restart verification to ensure this does not happen again.  It would be a good exercise for you.  We would just compare the results of the restarted case with a case without restart, point by point for the MLR vs. Time curve.  Do you want to give it a try?

**Comment by MortezaHaghighi** [comment]
Sorry for the late reply. I'm back from vacation now.
Yes, I'll make the case. One thing by the way; how to automate the stop-restart action?

**Comment by rmcdermo** [comment]
Well, in firebot it is already automated.  The "a" cases are run from `fds/Verification/FDS_Cases.sh` and the "b" cases are run from `fds/Verification/FDS_RESTART_Cases.sh`.  But these cases are already there.

You just need to add a base case to FDS_Cases.sh that will run the case from start to finish without restart, call this `PYRO3D_restart_base_case.fds` or something (put the case in the `fds/Verification/Restart/` directory).  Then compare the output with the restart case (point by point) to make sure they are identical.
