### ISSUE TITLE
PYRO3D_MASS_TRANSPORT issue

### ISSUE THREAD

**Issue by KRIShaiFU** [firemodels/fds#9002]
When I used the REFERENCE_TEMPERATURE on the MALT line, the errors occurred.  When I used the A and E on the MALT line, the program can be completed. What is the reason?

the errors and the code are shown :

 Time Step:      1, Simulation Time:      0.10 s
 Time Step:      2, Simulation Time:      0.20 s
 Time Step:      3, Simulation Time:      0.30 s
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
fds                00000000086A92C3  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FAF0149E370  Unknown               Unknown  Unknown
fds                00000000088B22CF  Unknown               Unknown  Unknown
fds                00000000088A01E6  Unknown               Unknown  Unknown
fds                0000000008873B99  Unknown               Unknown  Unknown
fds                0000000008782542  MAIN__                    778  main.f90
fds                00000000005525A2  Unknown               Unknown  Unknown
libc-2.17.so       00007FAEFF730B35  __libc_start_main     Unknown  Unknown
fds                0000000000552429  Unknown               Unknown  Unknown

&HEAD CHID='fire'/
&DUMP SMOKE3D=.TRUE., DT_PL3D=0.1, DT_RESTART=10.0, NFRAMES=1000/
&TIME T_END=500.0 /
&MISC SIMULATION_MODE='LES'/

&MESH ID='MESH', IJK=25,25,50, XB=0.0,5.0,0.0,5.0,0.0,10.0/

&SPEC ID='CARBON DIOXIDE'/
&SPEC ID = 'PS', FORMULA=C8H8/
&SPEC ID='OXYGEN', MASS_FRACTION_0=0.232/
&SPEC ID='WATER VAPOR'/
&SPEC ID='NITROGEN', MASS_FRACTION_0=0.768/

&REAC ID = 'RA1',
FUEL = 'PS',
SPEC_ID_NU='PS','OXYGEN','CARBON DIOXIDE', 'WATER VAPOR',
NU =-1,-10,8,4,
HEAT_OF_COMBUSTION = 10000./

&MATL ID='FOAM',
      SPECIFIC_HEAT=1.3,
      CONDUCTIVITY=0.08,
      DENSITY=25.0,
      HEAT_OF_COMBUSTION=10000.,
      N_REACTIONS=1,
      REFERENCE_TEMPERATURE=350.0,
      HEAT_OF_REACTION=1750.0,
      SPEC_ID(1:4,1)='PS','OXYGEN','CARBON DIOXIDE', 'WATER VAPOR',
      NU_SPEC(1:4,1)=1.0,0.0,0.0,0.0/

&MATL ID='CONCRETE',
      SPECIFIC_HEAT=1.04,
      CONDUCTIVITY=1.8,
      DENSITY=2280.0/

&SURF ID='XPS',
      RGB=0,255,255,
      MATL_ID='FOAM',
      BURN_AWAY=.TRUE.,
      HT3D=T/

&SURF ID='HunNingTu',
      RGB=192,192,192,
      NO_SLIP=.TRUE.,
      MATL_ID='CONCRETE',
      MATL_MASS_FRACTION=1.0,
      THICKNESS=0.1,
      CELL_SIZE_FACTOR=100.0/

&SURF ID='IGNITER',
      COLOR='RED',
      TMP_FRONT=1000.0,
      NO_SLIP=.TRUE./

&DEVC ID='TIMER1',XYZ=0.1,0.1,0.1,SETPOINT=50,QUANTITY='TIME',INITIAL_STATE=.TRUE./
&OBST XB=0.0,5.0,1.1,1.2,0.0,0.2, 
SURF_ID='IGNITER',
DEVC_ID='TIMER1'/ 

&OBST ID='Obstruction', XB=0.0,5.0,1.0,1.1,0.0,15.0, SURF_ID='XPS',  HT3D=T, PYRO3D_MASS_TRANSPORT=T, BULK_DENSITY=25.,THICKEN=T/
&OBST ID='Obstruction', XB=0.0,5.0,0.5,1.0,0.0,10.0, SURF_ID='HunNingTu'/ 

&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=5.0,5.0,0.0,5.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,0.0,5.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [YMAX]', SURF_ID='OPEN', XB=0.0,5.0,5.0,5.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [YMIN]', SURF_ID='OPEN', XB=0.0,5.0,0.0,0.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [ZMAX]', SURF_ID='OPEN', XB=0.0,5.0,0.0,5.0,10.0,10.0/ 
&VENT ID='Mesh Vent: MESH [ZMIN]', SURF_ID='OPEN', XB=0.0,5.0,0.0,5.0,0.0,0.0/ 

&BNDF QUANTITY='WALL TEMPERATURE'/
&BNDF QUANTITY='NET HEAT FLUX'/
&BNDF QUANTITY='BURNING RATE'/
&BNDF QUANTITY='INCIDENT HEAT FLUX'/
&BNDF QUANTITY='CONVECTIVE HEAT FLUX'/
&BNDF QUANTITY='RADIATIVE HEAT FLUX'/

&TAIL /

**Comment by rmcdermo** [comment]
Your problem is that you did not specify your formula with a string.  You should have:
```
&SPEC ID = 'PS', FORMULA='C8H8'/
```
I highly recommend you use a dedicated editor with FDS syntax highlighting.  I saw this instantly because of my editor.  I use [Sublime Text 3](https://www.sublimetext.com/3) with the [SublimeFDS](https://github.com/rmcdermo/SublimeFDS) plugin.

**Comment by KRIShaiFU** [comment]
> Your problem is that you did not specify your formula with a string. You should have:
> 
> ```
> &SPEC ID = 'PS', FORMULA='C8H8'/
> ```
> 
> I highly recommend you use a dedicated editor with FDS syntax highlighting. I saw this instantly because of my editor. I use [Sublime Text 3](https://www.sublimetext.com/3) with the [SublimeFDS](https://github.com/rmcdermo/SublimeFDS) plugin.

Thank you for your help very much.But I corrected the code, the errors occurred again.

**Comment by KRIShaiFU** [comment]
When I set REFERENCE_TEMPERATURE=250., the errors would disappear. Why?

**Comment by rmcdermo** [comment]
OK, I had gotten over the first crash and assumed we were good.

I am investigating the problem.  Not sure about REF_TMP right now.

**Comment by mcgratta** [comment]
I just realized that this is HT3D combined with BURN_AWAY.

Randy, is this allowed? The error occurs on line 3346 of func.f90, where MU_G (viscosity) is calculated. The subroutine is being sent ZZ_GET with all zeros and NaN for temperature. Haven't traced it back further than that.

**Comment by rmcdermo** [comment]
Yes, that is allowed.  In fact, it's the only way to shrink a material in 3D.

In degub, the case has a divide by zero because ZZP are all zeros at an outflow wall on the opposite side of the OBST.  I'm trying to track this down.

**Comment by KRIShaiFU** [comment]
When I added the code with bigger PYROLYSIS_RANGE, the errors would disappear too, such as REFERENCE_TEMPERATURE=350.0, PYROLYSIS_RANGE=200.. But, the REFERENCE_TEMPERATURE=200.0, PYROLYSIS_RANGE=50., is right. And, the small PYROLYSIS_RANGE could cause the errors to occur, such as REFERENCE_TEMPERATURE=350.0,
PYROLYSIS_RANGE=50..

**Comment by rmcdermo** [comment]
I suspect that the issue is PYRO3D_MASS_TRANSPORT=T.  This is really in very early stages of development.  Unless you are doing research in this area and want to help develop the mass transport routines, I suggest you simply use the default.

**Comment by rmcdermo** [comment]
@MortezaHaghighi Would you like to take a look at this?

**Comment by KRIShaiFU** [comment]
> I suspect that the issue is PYRO3D_MASS_TRANSPORT=T. This is really in very early stages of development. Unless you are doing research in this area and want to help develop the mass transport routines, I suggest you simply use the default.

Thank your very much for the answer. Your anwer is right in my case. It will solve my problem.

**Comment by MortezaHaghighi** [comment]
Yes, I feel the same... Whatever the bug is, it has to do with interchanging data at the face where the "slab solved by HT1D" touches the "slab solved by MT3D".
Make the 10m long slabs far away from each other (in the Y direction), and it works even with REFERENCE_TEMPERATURE=350.0! I'll see if I can dig out the code.

**Comment by KRIShaiFU** [comment]
I ran into a similar problem again, and I do not know why. I tried to simplify my model as much as possible, but the problem remained.


 Starting FDS ...
 MPI Process      0 started on node01
 Reading FDS input file ...
 Fire Dynamics Simulator
 Current Date     : December  5, 2020  00:08:59
 Revision         : FDS6.7.3-0-g9a07c36-release
 Revision Date    : Wed Oct 30 13:27:03 2019 -0500
 Compiler         : Intel ifort 19.0.4.243
 Compilation Date : Oct 31, 2019 08:45:55
 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:     20
 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2019 Update 4 for Linux* OS
 Job TITLE        : CONTINUOUS CASE
 Job ID string    : spreadfire
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
fds                00000000086A92C3  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FE3E5E14370  Unknown               Unknown  Unknown
fds                00000000089AE660  Unknown               Unknown  Unknown
fds                0000000008780CC6  MAIN__                    594  main.f90
fds                00000000005525A2  Unknown               Unknown  Unknown
libc-2.17.so       00007FE3E40A6B35  __libc_start_main     Unknown  Unknown
fds                0000000000552429  Unknown               Unknown  Unknown



code:
&HEAD CHID='spreadfire',TITLE='CONTINUOUS CASE'/
&DUMP SMOKE3D=.TRUE., DT_PL3D=0.1, NFRAMES=1000/
&TIME T_END=600.0 /

&MESH ID='MESH3', IJK=50,50,100, XB=0.0,5.0,0.0,5.0,0.0,10.0/

&SPEC ID='CARBON DIOXIDE'/
&SPEC ID = 'PS', FORMULA='C8H8'/
&SPEC ID='OXYGEN', MASS_FRACTION_0=0.232/
&SPEC ID='WATER VAPOR'/
&SPEC ID='NITROGEN', MASS_FRACTION_0=0.768/


&REAC ID = 'RA1',
FUEL='PS',
SPEC_ID_NU='PS','OXYGEN','CARBON DIOXIDE', 'WATER VAPOR',
NU =-1,-10,8,4,
HEAT_OF_COMBUSTION = 25000./

&MATL ID='FOAM',
      SPECIFIC_HEAT=1.3,
      CONDUCTIVITY=0.08,
      DENSITY=25.0,
      HEAT_OF_COMBUSTION=25000.,
      N_REACTIONS=1,
      REFERENCE_TEMPERATURE=350.0,
      PYROLYSIS_RANGE=130.,
      HEAT_OF_REACTION=1750.0,
      SPEC_ID(1:4,1)='PS','OXYGEN','CARBON DIOXIDE', 'WATER VAPOR',
      NU_SPEC(1:4,1)=1.0,0.0,0.0,0.0/


&SURF ID='XPS',
      RGB=0,255,255,
      MATL_ID='FOAM',
      BURN_AWAY=.TRUE.,
      HT3D=T/

&SURF ID='IGNITER',
      COLOR='RED',
      TMP_FRONT=2000.0,
      NO_SLIP=.TRUE./

&OBST XB=0.0,5.0,1.0,1.2,0.5,0.8, 
SURF_ID='IGNITER'/ 

&OBST ID='Obstruction', XB=0.0,5.0,1.0,1.2,1.0,10.0, SURF_ID='XPS',  HT3D=T, BULK_DENSITY=25.,THICKEN=T/

&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=5.0,5.0,0.0,5.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,0.0,5.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [YMAX]', SURF_ID='OPEN', XB=0.0,5.0,5.0,5.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [YMIN]', SURF_ID='OPEN', XB=0.0,5.0,0.0,0.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [ZMAX]', SURF_ID='OPEN', XB=0.0,5.0,0.0,5.0,10.0,10.0/ 
&VENT ID='Mesh Vent: MESH [ZMIN]', SURF_ID='OPEN', XB=0.0,5.0,0.0,5.0,0.0,0.0/ 

&BNDF QUANTITY='WALL TEMPERATURE'/
&BNDF QUANTITY='NET HEAT FLUX'/
&BNDF QUANTITY='BURNING RATE'/
&BNDF QUANTITY='INCIDENT HEAT FLUX'/
&BNDF QUANTITY='CONVECTIVE HEAT FLUX'/
&BNDF QUANTITY='RADIATIVE HEAT FLUX'/

&TAIL /

**Comment by MortezaHaghighi** [comment]
Are you using the latest code? I ran your input file and it is working fine until 2 seconds of simulation.
mine is FDS6.7.5-614-g8878d2aa7-master

**Comment by KRIShaiFU** [comment]
> Are you using the latest code? I ran your input file and it is working fine until 2 seconds of simulation.
> mine is FDS6.7.5-614-g8878d2aa7-master

Thank your very much. I think there's something wrong with my computer. I ran the input file and it is working fine on the other computer.

**Comment by rmcdermo** [comment]
Looks like this is fixed.
