### ISSUE TITLE
Smokeview pictures script changed behavior

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9247]
@gforney I happened upon this today while trying to revamp the `fds/Verification/Turbulence/ribbed_channel*` test series.  In this verification case take a snapshot of velocities vectors flowing over the rib.  The first image below is from `FDS6.7.5-772-g51bc92754`.  The second image is from last nights build.

<img width="1429" alt="Screen Shot 2021-02-18 at 1 36 07 PM" src="https://user-images.githubusercontent.com/4418497/108405097-af2c4000-71ee-11eb-9d73-50ee78ff7b29.png">

<img width="1429" alt="Screen Shot 2021-02-18 at 1 35 39 PM" src="https://user-images.githubusercontent.com/4418497/108405113-b2bfc700-71ee-11eb-9261-a706e809dc92.png">

I've made the case before that we need to have a base set of images and do some kind of comparison with firebot to catch these deviations.

**Comment by gforney** [comment]
check the manual from last night's firebot.  should be fixed.  some recent changes in smokeview broke the SETVIEWPOINT script command .  While you are at it check other figures in the guides.  Any figure generated that used SETVIEWPOINT was probably also broken.

**Comment by rmcdermo** [comment]
Thanks, yes, the figure is fixed.  Let's leave this open until we get the figure checking implemented.

**Comment by gforney** [comment]
did you mean to say not fixed?  this is what I'm seeing in the manual produced last night.  

<img width="648" alt="ribbed_021921" src="https://user-images.githubusercontent.com/12403014/108511203-92931500-728d-11eb-804c-79a8b9062f1d.png">

**Comment by rmcdermo** [comment]
Sorry!  I meant it has been fixed.
