### ISSUE TITLE
Wind impacting unrelated vents

### ISSUE THREAD

**Issue by A-Milford** [firemodels/fds#9504]
After observing some unexpected results for some simulations with a building with exterior wind, we have explored further with some simple test cases and appear to be seeing the WIND functionality impacting airflow from vent surfaces within the domain intended for exhaust/supply.

For our test case we have a simple partial enclosure with one open end at the downstream side and an exhaust vent surface inside (shown selected in the image below), intended to have the following ramp behaviour:

&SURF ID='Fan',
      RGB=26,204,26,
      VOLUME_FLOW=50.0,
      RAMP_V='Fan_RAMP_V'/
&RAMP ID='Fan_RAMP_V', T=0.0, F=0.0/
&RAMP ID='Fan_RAMP_V', T=30.0, F=0.0/
&RAMP ID='Fan_RAMP_V', T=90.0, F=1.0/
&RAMP ID='Fan_RAMP_V', T=300.0, F=1.0/

![image](https://user-images.githubusercontent.com/84096249/118051239-7dca9880-b335-11eb-884a-b0765193b16c.png)

We compared the airflow through the enclosure for two baseline cases (1. exhaust fan operating with no wind, and 2. wind included with no fan operation), using the following WIND implementation:

&WIND L=1.0E6, Z_0=1.0, Z_REF=10.0, SPEED=4.0/

When the exhaust fan and the wind field are used in conjunction we are seeing supply airflow from the vent during the period of the ramp where there should be no airflow, followed by an offset ramp that does end up at the defined flow rate after 90 seconds.  A second case was run with the exhaust vent activated at 30 seconds, which yielded a spike in the supply direction, followed by the same offset ramp. A plot of the airflow is included below,and I have attached a txt file of the fan operation case. 

![image](https://user-images.githubusercontent.com/84096249/118050492-3bed2280-b334-11eb-9303-261ca3201fb1.png)

[Fan_ramp.txt](https://github.com/firemodels/fds/files/6469310/Fan_ramp.txt)

I'm curious if the wind implementation is creating an offset in what is considered to be 'zero' for the exhaust vent, as further tests have shown the same ~+10 m3/s when the ramp should be 0 or upon delayed activation of the vent if a supply vent is used instead of exhaust. Surrounding the enclosure and vent with a hole with Block_wind=.true. had no impact on the results.

**Comment by A-Milford** [comment]
I should mention the FDS revision information:

 Fire Dynamics Simulator

 Current Date     : May 12, 2021  15:29:03
 Revision         : FDS6.7.5-0-g71f025606-release
 Revision Date    : Thu Aug 20 16:19:01 2020 -0400
 Compiler         : Intel ifort 19.1.1.216
 Compilation Date : Fri 08/21/2020  04:51 PM

**Comment by rmcdermo** [comment]
Thank for the report.  We will take a look.

**Comment by mcgratta** [comment]
These WIND parameters are intended for an OPEN domain; that is, OPEN on all
sides and top. I suggest you specify a VEL at the back wall.

>

**Comment by rmcdermo** [comment]
@A-Milford I think this is related to the use of MEAN_FORCING.  Note that we have deprecated MEAN_FORCING in the up coming v6.7.6.  Try your cases using the latest test bundle, which is linked at the top of [FDS Release Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes).  Let me know if this solves your problem.

**Comment by A-Milford** [comment]
@rmcdermo Thanks for the quick reply.  I have tried running the test case with latest test bundle that I downloaded this morning and the issue persists.
 
Fire Dynamics Simulator

 Current Date     : May 14, 2021  10:17:05
 Revision         : FDS6.7.5-1499-gd51ed31f1-nightly
 Revision Date    : Thu May 13 16:17:27 2021 -0400
 Compiler         : Intel ifort 2021.1
 Compilation Date : Fri 05/14/2021  08:51 AM


I ran a few other tests and observed something interesting - if the vent surface is re-oriented to be either in the Z or Y planes (on the floor or roof of the enclosure or on the sidewalls, the flowrate issue is resolved and the ramp function works to specify the exhaust rate as intended (the wind direction is specified to be in the +X direction). It appears the vent surface exhaust flowrate is only impacted if it is perpendicular to specified wind airflow.

I have tried using a surface with a VEL instead of a vent, and the same flowrate issue is observed. Similarly, using OPEN on all the sides and top of the domain does not have an impact. 

Edit: updated input file attached
[Fan_ramp_sidewall.txt](https://github.com/firemodels/fds/files/6480354/Fan_ramp_sidewall.txt)

**Comment by rmcdermo** [comment]
@A-Milford Then the issue sounds like a velocity penetration error problem, which is resolved by tightening the velocity tolerance on the PRES line, for example:
```
&PRES VELOCITY_TOLERANCE=0.0001, MAX_PRESSURE_ITERATIONS=100/
```
You can also monitor the velocity error using a BNDF:
```
BNDF QUANTITY='VELOCITY ERROR', CELL_CENTERED=T/
```
Try this and let me know if it helps.

**Comment by A-Milford** [comment]
@rmcdermo Thanks for the feedback and recommendation. Adding the lines above does not appear to have an impact, and we're still seeing around 10 m3/s of supply through the enclosure when the fan ramp is at 0. The boundary output for velocity error fluctuates a bit, but at the location of the vent it is generally ~0.0003 m/s or smaller:

![image](https://user-images.githubusercontent.com/84096249/118666961-7299c180-b7a8-11eb-8568-8b5e3e5f5b84.png)

**Comment by rmcdermo** [comment]
@A-Milford I am seeing the same problem you are seeing.  The problem is that U0 has historically been set as a "WIND" for a VENT type boundary condition.  Now, U0 gets applied and ramped for OPEN as well as part of the newer WIND boundaries.  This parameter is not currently independent for other SOLID_BOUNDARIES.  We need to decouple this.

@mcgratta Do we still want to have U0 attached to a SOLID_BOUNDARY?  Given the way we treat WIND now, I don't see why we need it there.  Here is a simplified version of the case that runs in a couple minutes.  The VOLUME FLOW WALL in the _devc file should be 0 for 10 s then ramp linearly to 50 for 10 s.

[Fan_ramp.fds.txt](https://github.com/firemodels/fds/files/6504166/Fan_ramp.fds.txt)

**Comment by mcgratta** [comment]
Agreed. This looks like a remnant of the old wall o' wind days. I'll remove it and run the verification cases to see if there's some old cases that still rely on this.

**Comment by mcgratta** [comment]
The verification cases passed. Try your case now.

**Comment by rmcdermo** [comment]
The case seems to work, but there is some kind of initialization bug.  Even with `NOISE=F` the first line of the _devc file has erroneous values.
```
s,m3/s,m3/s
Time,"FLOW","WALL FLOW"
 0.0000000E+000, 4.5233409E+000, 2.7670803E+000
 9.1034758E-002, 2.7454246E-004, 2.7755576E-017
 1.8206952E-001, 2.7279965E-004, 3.0814879E-033
...
```

**Comment by mcgratta** [comment]
We are setting U, V, W to U0, V0, and W0 initially, everywhere. Otherwise,
if we set the velocity to zero initially, it will take time for the wind
field to establish.

>

**Comment by rmcdermo** [comment]
Right, forgot about that.
@A-Milford Please see if this fixes your case (you can get the bundle [here](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC)) and close if so.  Thanks

**Comment by mcgratta** [comment]
If t=0 is a critical part of the analysis, it might be a good idea to set
`T_BEGIN=-10` or whatever to allow the wind field to fully establish around
the obstructions.

**Comment by A-Milford** [comment]
@rmcdermo I ran both my original test case and your simplified test case with the latest bundle for windows (FDS6.7.5-1509-gcecc7d470-nightly) and the issue is unchanged. Judging by the bundle names and the revision date for 1509 (May 15), I think the windows bundle is not as recently updated as the Linux/OSX bundles (1526), am I interpreting that correctly?

**Comment by rmcdermo** [comment]
@A-Milford Yes, you are correct.

@gforney Can you please upload the latest windows bundle?  Thanks

**Comment by gforney** [comment]
looks like you missed the updated bundle by a few minutes.  I updated it earlier when I was at work rebooting burn.  It should be up to date now

**Comment by A-Milford** [comment]
@rmcdermo I've re-run with the updated bundle (fds6.7.5-1526)  and the issue is resolved. Thanks for the assistance, much appreciated.

**Comment by rmcdermo** [comment]
Excellent.  This was a good catch.  Up for a Boris!
